<Workspace Version="1.3.3.4651" X="-1479.03728094774" Y="143.556133517222" zoom="0.697954069764928" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Categories guid="4fb9a7a8-66e3-4d88-82e2-0cb548f0f436" type="DSRevitNodesUI.Categories" nickname="Categories" x="-922.873745128206" y="-402.160149376516" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="414:Floors" />
    <DSRevitNodesUI.Categories guid="709f95ff-5930-465e-95bb-2b560c9c2cc6" type="DSRevitNodesUI.Categories" nickname="Categories" x="-954.097236802655" y="564.395033961257" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="493:SpecialityEquipment" />
    <DSRevitNodesUI.ElementsOfCategory guid="5a928c1e-ecd5-4ce1-b678-a7022de416a2" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="-676.80897322751" y="-402.955126158529" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.ElementsOfCategory guid="e4bed208-0f49-45b5-9564-4d01ab269c18" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="-683.261262195858" y="565.165304995085" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="efee5583-47bf-4801-b0f7-6011a85388eb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="1631.74102044105" y="49.2930051818128" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Prorubim.DS.Common.ForceChildrensEval guid="7e24238b-75b8-4c75-82bb-559b1dcaa6fa" type="Prorubim.DS.Common.ForceChildrensEval" nickname="ForceChildrensEval" x="2216.03590889389" y="-4.69196568588954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </Prorubim.DS.Common.ForceChildrensEval>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="068a048b-141d-4fc8-bc42-5e1006dcef00" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2026.8166018214" y="-275.109800492461" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="Flor;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="86f556dd-7351-4d46-8f62-bfbb19dd133a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="1629.04957074327" y="-67.6724092071325" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="1ed1c4f1-dc98-4357-b3b3-1cda86e85045" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2940.05664837417" y="121.705584927264" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>if IN[3] == False:
	import clr

clr.AddReference('RevitAPI')
import Autodesk

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

dataEnteringNode = IN

reset = IN[0]
items1 = UnwrapElement(IN[1])
items2 = UnwrapElement(IN[2])

doc = DocumentManager.Instance.CurrentDBDocument

results = []

TransactionManager.Instance.EnsureInTransaction(doc)
for item1 in items1:
	for item2 in items2:
		try:
			result = Autodesk.Revit.DB.InstanceVoidCutUtils.RemoveInstanceVoidCut(doc,item1,item2)
			results.append(result)
		except:
			pass
TransactionManager.Instance.TransactionTaskDone()

OUT = results</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="4975702f-0662-4c1d-b261-7ec3bf0e3ca3" type="CoreNodeModels.Input.BoolSelector" nickname="Вырезание геометрии/Отмена вырезания " x="2220.29670317278" y="226.968000837951" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="041080bb-6e53-456f-8ca1-9623ff2ee0ef" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2013.17568616026" y="106.891652840913" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="shaft;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="04629afd-d979-426f-be4f-d69b09e05ad2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2930.11299281259" y="-177.100745540791" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>if IN[3] == True:
	import clr

clr.AddReference('RevitAPI')
import Autodesk

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

reset = IN[0]
items1 = UnwrapElement(IN[1])
items2 = UnwrapElement(IN[2])

doc = DocumentManager.Instance.CurrentDBDocument

TransactionManager.Instance.EnsureInTransaction(doc)
for item1 in items1:
	for item2 in items2:
		try:
			result = Autodesk.Revit.DB.InstanceVoidCutUtils.AddInstanceVoidCut(doc,item1,item2)
		except:
			pass
TransactionManager.Instance.TransactionTaskDone()
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4fb9a7a8-66e3-4d88-82e2-0cb548f0f436" start_index="0" end="5a928c1e-ecd5-4ce1-b678-a7022de416a2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="709f95ff-5930-465e-95bb-2b560c9c2cc6" start_index="0" end="e4bed208-0f49-45b5-9564-4d01ab269c18" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a928c1e-ecd5-4ce1-b678-a7022de416a2" start_index="0" end="068a048b-141d-4fc8-bc42-5e1006dcef00" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e4bed208-0f49-45b5-9564-4d01ab269c18" start_index="0" end="041080bb-6e53-456f-8ca1-9623ff2ee0ef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e24238b-75b8-4c75-82bb-559b1dcaa6fa" start_index="0" end="1ed1c4f1-dc98-4357-b3b3-1cda86e85045" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e24238b-75b8-4c75-82bb-559b1dcaa6fa" start_index="0" end="04629afd-d979-426f-be4f-d69b09e05ad2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="068a048b-141d-4fc8-bc42-5e1006dcef00" start_index="0" end="1ed1c4f1-dc98-4357-b3b3-1cda86e85045" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="068a048b-141d-4fc8-bc42-5e1006dcef00" start_index="0" end="04629afd-d979-426f-be4f-d69b09e05ad2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4975702f-0662-4c1d-b261-7ec3bf0e3ca3" start_index="0" end="1ed1c4f1-dc98-4357-b3b3-1cda86e85045" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4975702f-0662-4c1d-b261-7ec3bf0e3ca3" start_index="0" end="04629afd-d979-426f-be4f-d69b09e05ad2" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="041080bb-6e53-456f-8ca1-9623ff2ee0ef" start_index="0" end="1ed1c4f1-dc98-4357-b3b3-1cda86e85045" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="041080bb-6e53-456f-8ca1-9623ff2ee0ef" start_index="0" end="04629afd-d979-426f-be4f-d69b09e05ad2" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="9eabd188-9792-4b83-8faa-dd9c3dffc5a7" annotationText="Элементы геометрии внутри динамо, для визуальной проверки" left="1619.04957074327" top="-127.672409207133" width="219.69144969778" height="269.965414388945" fontSize="14" InitialTop="-67.6724092071325" InitialHeight="239.965414388945" TextblockHeight="50" backgrouund="#FF848484">
      <Models ModelGuid="efee5583-47bf-4801-b0f7-6011a85388eb" />
      <Models ModelGuid="86f556dd-7351-4d46-8f62-bfbb19dd133a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-29.902379989624" eyeY="58.628059387207" eyeZ="58.9241218566895" lookX="28.8355369567871" lookY="-54.628059387207" lookZ="-61.3081588745117" upX="0.189906880259514" upY="0.894934356212616" upZ="-0.403767108917236" />
  </Cameras>
</Workspace>
